### ISSUE TITLE
Merged and not Merged

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecDatasets#82]
What is the difference between merged and not merged folders from the converted atomic files on Google Drive?

**Comment by hyp1231** [comment]
Interactions between the same pair of user and item may appear more than once, e.g. one user purchases the same kind of bread many times.

Thus, ``merged`` means we remain *at most one* interaction for a pair of user and item (also means have removed duplicated user-item interactions) after generating the atomic files, and ``not_merged`` vice versa.

For more details, you may also refer to [issue 487](https://github.com/RUCAIBox/RecBole/issues/487) from RecBole Repo.

**Comment by johnny12150** [comment]
Ok. Thanks a lot!
