### ISSUE TITLE
How to convert my own dataset

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecDatasets#86]
Hi I would like to convert my own dataset into atomic files so I can run RecBole.
I'm not sure how to use these convertors. 
Thanks for any guidence

**Comment by hyp1231** [comment]
Please refer to [https://github.com/RUCAIBox/RecBole/discussions/607#discussioncomment-236083](https://github.com/RUCAIBox/RecBole/discussions/607#discussioncomment-236083).
